### ISSUE TITLE
"Don't delete" option please

### ISSUE THREAD

**Issue by sochartetu** [zaytiri/handbrake-recursive-folder-video-converter#11]
I am using HAVC on a distant server because of computing capacities.
The folder containing videos to be converted is on another network through WAN.

I'd like to see an option to disable the delete functionality and leave files where they are because it consumes
bandwidth and takes time to to a round-trip around Internet through SMB to copy a file to another folder on the same machine.

Thanks.

**Comment by zaytiri** [comment]
I just released version 1.4.0 which should contain the solution to this problem.

Let me know if it works fine for you so we can also close this issue. Thanks!

**Comment by sochartetu** [comment]
Thanks a lot,
I will definitely try it right now.


De : lia ***@***.***>
Envoyé : 9 octobre 2024 18:33
À : zaytiri/handbrake-recursive-folder-video-converter ***@***.***>
Cc : Sébastien Ochart ***@***.***>; Author ***@***.***>
Objet : Re: [zaytiri/handbrake-recursive-folder-video-converter] "Don't delete" option please (Issue #11)

ATTENTION: Ce courriel provient de l'extérieur du Cégep. Ne cliquez pas sur les liens ou n'ouvrez pas les pièces jointes à moins de reconnaître l'expéditeur et de savoir que le contenu est sécurisé.


I just released version 1.4.0 which should contain the solution to this problem.

Let me know if it works fine for you so we can also close this issue. Thanks!

-

**Comment by sochartetu** [comment]
Thanks a lot, it works beautifully and is much faster.
