### ISSUE TITLE
 Could not find a version that satisfies the requirement havc (from versions: none)

### ISSUE THREAD

**Issue by Waffled-II** [zaytiri/handbrake-recursive-folder-video-converter#9]
I run:
pip3 --no-cache-dir install havc

but i get an error:

ERROR: Could not find a version that satisfies the requirement havc (from versions: none)
ERROR: No matching distribution found for havc

**Comment by zaytiri** [comment]
Hi, I will try to investigate the problem. I'll get back to you.

**Comment by zaytiri** [comment]
I tried installing in my machine, and it worked fine. I'm using python version > 3.12. 
This package requires at least the version >=3.10.6. Do you perhaps use a previous version than 3.10.6?
